(()=>{'use strict';
const STATE_KEY='contractorSearchCollapsedV1';
const $=id=>document.getElementById(id);
function summaryText(){const loc=$('location')?.value.trim()||'Location';const type=$('contractorType')?.value.trim()||'Contractor type';return `${loc} · ${type}`}
function setCollapsed(card,body,toggle,collapsed,persist=true){card.classList.toggle('search-options-collapsed',collapsed);body.hidden=collapsed;toggle.setAttribute('aria-expanded',collapsed?'false':'true');const s=toggle.querySelector('.search-options-summary');if(s)s.textContent=summaryText();if(persist)try{localStorage.setItem(STATE_KEY,collapsed?'1':'0')}catch{}}
function install(){const settings=$('settings'),loc=$('location'),searchBtn=$('searchBtn');if(!settings||!loc||!searchBtn)return;const card=loc.closest('section.card');if(!card||card.classList.contains('search-options-card'))return;card.classList.add('search-options-card');const children=[...card.childNodes];const body=document.createElement('div');body.className='search-options-body';children.forEach(n=>body.appendChild(n));const toggle=document.createElement('button');toggle.type='button';toggle.className='search-options-toggle';toggle.innerHTML='<span class="search-options-toggle-main"><span class="search-options-toggle-title">Search options</span><span class="search-options-summary"></span></span><span class="search-options-chevron">⌃</span>';card.append(toggle,body);let saved=false;try{saved=localStorage.getItem(STATE_KEY)==='1'}catch{}setCollapsed(card,body,toggle,saved,false);toggle.addEventListener('click',()=>{const next=!card.classList.contains('search-options-collapsed');if(!next&&settings.open)settings.open=false;setCollapsed(card,body,toggle,next)});settings.addEventListener('toggle',()=>{if(settings.open)setCollapsed(card,body,toggle,true)});['input','change'].forEach(ev=>body.addEventListener(ev,()=>{const s=toggle.querySelector('.search-options-summary');if(s)s.textContent=summaryText()}));searchBtn.addEventListener('click',()=>setTimeout(()=>setCollapsed(card,body,toggle,true),0),false);$('refreshBtn')?.addEventListener('click',()=>setTimeout(()=>setCollapsed(card,body,toggle,true),0),false);const currentResults=$('currentResults');if(currentResults){const obs=new MutationObserver(()=>{if(currentResults.children.length)setCollapsed(card,body,toggle,true)});obs.observe(currentResults,{childList:true});}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
