(()=>{'use strict';
const DB='contractor-finder-edwin',VER=1,API='https://api.outscraper.cloud';
const DETAIL_TTL=24*60*60*1000,PHOTO_TTL=14*24*60*60*1000,PHOTO_LIMIT=30;
let db=null,lastLocation='',loading=false,current=null;
const $=id=>document.getElementById(id),N=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' '),NOW=()=>new Date().toISOString(),S=ms=>new Promise(r=>setTimeout(r,ms));
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function age(ts){const n=Date.parse(ts||'');return Number.isFinite(n)?Date.now()-n:Infinity}
function ageText(ts){const ms=age(ts);if(ms<3600000)return'just now';if(ms<86400000)return Math.floor(ms/3600000)+'h ago';return Math.floor(ms/86400000)+'d ago'}
function domain(url){if(!url)return'';try{return new URL(/^https?:/i.test(url)?url:'https://'+url).hostname.replace(/^www\./,'')}catch{return''}}
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function store(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
function get(n,k){return new Promise((ok,no)=>{const r=store(n).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function put(n,v){return new Promise((ok,no)=>{const r=store(n,'readwrite').put(v);r.onsuccess=()=>ok(v);r.onerror=()=>no(r.error)})}
async function setting(k,d=null){const r=await get('settings',k);return r?r.value:d}
async function saveSetting(k,v){return put('settings',{key:k,value:v,updatedAt:NOW()})}
function flatten(data){let x=data?.data??data;if(!Array.isArray(x))return[];while(x.length===1&&Array.isArray(x[0]))x=x[0];return x.flat(Infinity).filter(v=>v&&typeof v==='object'&&!Array.isArray(v))}
async function api(path,params={}){const key=String(await setting('apiKey','')).trim();if(!key)throw Error('Save your Outscraper API key first.');const u=new URL(API+path);for(const[k,v]of Object.entries(params)){if(v===undefined||v===null||v==='')continue;if(Array.isArray(v))v.forEach(x=>u.searchParams.append(k,String(x)));else u.searchParams.set(k,String(v))}u.searchParams.set('apiKey',key);let r;try{r=await fetch(u,{mode:'cors',credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer'})}catch{throw Error('Safari could not reach Outscraper for the Site Profile.')}const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok)throw Error(d?.errorMessage||d?.message||('Outscraper HTTP '+r.status));return d}
async function resolve(d,label){const s=N(d?.status);if(s==='success'||!d?.id)return d;if(s==='failure')throw Error(label+' failed.');for(let i=1;i<=45;i++){status(label+' running… '+i+'/45');await S(i<4?1800:2800);const x=await api('/requests/'+encodeURIComponent(d.id),{flat:'true'}),xs=N(x?.status);if(xs==='success')return x;if(xs==='failure')throw Error(label+' failed.')}throw Error(label+' is still pending. Try Refresh site again shortly.')}
function isFullAddress(q){q=String(q||'').trim();if(!q||/^\d{5}(?:-\d{4})?$/.test(q))return false;if(/^[-a-z .']+,\s*[a-z]{2,}(?:\s+\d{5})?$/i.test(q)&&!/\d/.test(q))return false;return /\d{1,7}\s+[^,]+/.test(q)||/(street|\bst\b|avenue|\bave\b|road|\brd\b|boulevard|\bblvd\b|drive|\bdr\b|highway|\bhwy\b|parkway|\bpkwy\b|lane|\bln\b|court|\bct\b|place|\bpl\b)\b/i.test(q)&&/,/.test(q)}
function cacheKey(q){return'siteProfileV4:'+N(q)}
function mapScore(r,q){let score=0,a=N(r.full_address||r.address||''),num=(String(q).match(/\b(\d{1,7})\b/)||[])[1];if(num&&a.includes(num))score+=10;if(r.name)score+=2;if(r.phone)score+=1;if(r.site||r.website)score+=1;if(r.logo)score+=3;if(r.photo)score+=2;if(r.street_view)score+=2;if(N(r.business_status).includes('operational'))score+=1;const words=N(q).split(/[^a-z0-9]+/).filter(x=>x.length>3);score+=Math.min(6,words.filter(w=>a.includes(w)).length);return score}
function normalize(r,q){const site=r.site||r.website||'';return{name:r.name||'Site / Property',address:r.full_address||r.address||q,category:r.category||r.type||'',subtypes:Array.isArray(r.subtypes)?r.subtypes.join(', '):(r.subtypes||''),phone:r.phone||'',site,rating:Number.isFinite(+r.rating)?+r.rating:null,reviews:Number.isFinite(+r.reviews)?+r.reviews:null,status:r.business_status||'',hours:r.working_hours||r.working_hours_csv_compatible||'',logo:r.logo||'',photo:r.photo||'',streetView:r.street_view||'',photosCount:Number.isFinite(+r.photos_count)?+r.photos_count:null,locatedIn:r.located_in||'',plusCode:r.plus_code||'',placeId:r.place_id||'',googleId:r.google_id||'',cid:r.cid||'',map:r.location_link||r.google_maps_url||r.reviews_link||'',city:r.city||'',state:r.state||r.us_state||'',postal:r.postal_code||'',logoFallback:site?`https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain(site))}&sz=128`:''}}
function hours(v){if(!v)return'';if(typeof v==='string')return v.replace(/\|/g,' · ');if(typeof v==='object'){const es=Object.entries(v);if(!es.length)return'';const today=new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date()),hit=es.find(([k])=>N(k)===N(today));if(hit)return`${hit[0]}: ${Array.isArray(hit[1])?hit[1].join(', '):hit[1]}`;return es.slice(0,2).map(([k,x])=>`${k}: ${Array.isArray(x)?x.join(', '):x}`).join(' · ')}return''}
function status(t){const e=$('spStatus');if(e)e.textContent=t||''}
function createPanel(){const s=document.createElement('section');s.id='siteProfileV4';s.className='site-profile';s.innerHTML=`<div class="site-profile-head"><div class="site-profile-id"><img id="spLogo" class="site-profile-logo sp-hidden" alt="Business logo"><div style="min-width:0"><div class="site-profile-kicker">Site Profile</div><div class="site-profile-name" id="spName">No full street address selected</div><div class="site-profile-address" id="spAddress">Enter a full street address to load site/business details and public photos.</div><div class="site-profile-nearby" id="spNearby"></div></div></div><button class="site-profile-refresh" id="spRefresh" type="button">Refresh site</button></div><div class="site-profile-main"><div class="site-profile-details" id="spDetails"><div class="site-profile-empty">ZIP/city searches still work for contractors. The Site Profile activates for a street address.</div></div><div class="site-profile-gallery"><div class="site-profile-gallery-head"><span>Building / surroundings / parking / public photos</span><span id="spPhotoCount"></span></div><div class="site-profile-photos" id="spPhotos"></div></div></div><div class="site-profile-status" id="spStatus"></div>`;return s}
function installLayout(){const shell=document.querySelector('.shell');if(!shell||shell.classList.contains('site-layout'))return;const top=shell.querySelector('.topbar'),search=top?.nextElementSibling,settings=$('settings'),tabs=shell.querySelector('.main-tabs');if(!top||!search||!settings||!tabs)return;const panel=createPanel(),fixed=document.createElement('div');fixed.className='site-fixed-zone';shell.insertBefore(fixed,top);fixed.append(top,search,settings,panel);const scroll=document.createElement('div');scroll.className='site-results-scroll';scroll.id='siteResultsScroll';shell.insertBefore(scroll,tabs);let n=scroll.nextSibling;while(n){const next=n.nextSibling;scroll.appendChild(n);n=next}shell.classList.add('site-layout');$('spRefresh').addEventListener('click',()=>load(($('location')?.value||'').trim(),true));}
function clearPanel(message='Enter a full street address to load site/business details and public photos.'){current=null;const logo=$('spLogo');if(logo){logo.classList.add('sp-hidden');logo.removeAttribute('src')}$('spName').textContent='No full street address selected';$('spAddress').textContent=message;$('spNearby').textContent='';$('spDetails').innerHTML='<div class="site-profile-empty">ZIP/city searches still work for contractors. The Site Profile activates for a street address.</div>';$('spPhotos').innerHTML='';$('spPhotoCount').textContent='';status('')}
function photoHtml(p){return`<a class="site-profile-photo" href="${E(p.url)}" target="_blank" rel="noopener"><img loading="lazy" referrerpolicy="no-referrer" src="${E(p.url)}" alt="${E(p.label)}" onerror="this.closest('.site-profile-photo').style.display='none'"><span>${E(p.label)}</span></a>`}
function render(p){current=p;if(!p){clearPanel();return}const logo=$('spLogo'),lu=p.logo||p.logoFallback||'';if(lu){logo.src=lu;logo.classList.remove('sp-hidden');logo.onerror=()=>logo.classList.add('sp-hidden')}else logo.classList.add('sp-hidden');$('spName').textContent=p.name||'Site / Property';$('spAddress').textContent=p.address||p.query||'';const at=(p.businesses||[]).map(x=>x.name).filter(Boolean);$('spNearby').textContent=at.length>1?'At/near this address: '+at.slice(0,5).join(' · '):'';const web=p.site?(/^https?:/i.test(p.site)?p.site:'https://'+p.site):'',rating=Number.isFinite(p.rating)?`${p.rating.toFixed(1)}${Number.isFinite(p.reviews)?' / '+p.reviews.toLocaleString()+' reviews':''}`:'';const vals=[['Business / category',p.category||p.subtypes||'Not identified'],['Status',p.status||'Not returned'],['Phone',p.phone?`<a href="tel:${E(String(p.phone).replace(/[^\d+]/g,''))}">${E(p.phone)}</a>`:'Not returned',1],['Website',web?`<a href="${E(web)}" target="_blank" rel="noopener">${E(domain(web)||p.site)}</a>`:'Not returned',1],['Rating',rating||'Not returned'],['Hours',hours(p.hours)||'Not returned'],['Located in',p.locatedIn||'Standalone / not returned'],['ZIP / Plus Code',[p.postal,p.plusCode].filter(Boolean).join(' · ')||'Not returned']];$('spDetails').innerHTML=vals.map(([k,v,raw])=>`<div class="site-profile-detail"><b>${E(k)}</b><span>${raw?v:E(v)}</span></div>`).join('');const photos=p.photos||[];$('spPhotos').innerHTML=photos.map(photoHtml).join('')||'<div class="site-profile-empty">No public place photos were returned for this site.</div>';const total=p.photosCount||photos.length;$('spPhotoCount').textContent=photos.length?(total>photos.length?`${photos.length} shown / ${total} reported`:`${photos.length} photo${photos.length===1?'':'s'}`):'';const st=$('spStatus');st.textContent=`Site info refreshed ${ageText(p.refreshedAt)}${p.photosRefreshedAt?' · photos '+ageText(p.photosRefreshedAt):''}`;if(p.map){const a=document.createElement('a');a.href=p.map;a.target='_blank';a.rel='noopener';a.textContent=' · Map listing';st.appendChild(a)}}
async function details(q){let d=await api('/google-maps-search',{query:q,limit:8,dropDuplicates:'true',language:'en',region:'US',async:'false'});d=await resolve(d,'Site lookup');const rows=flatten(d);if(!rows.length)return null;const ranked=rows.map(r=>({r,score:mapScore(r,q)})).sort((a,b)=>b.score-a.score),p=normalize(ranked[0].r,q);p.businesses=ranked.slice(0,6).map(x=>normalize(x.r,q));p.query=q;return p}
async function photos(p,q){const out=[],seen=new Set(),add=(u,l)=>{if(u&&!seen.has(u)){seen.add(u);out.push({url:u,label:l})}};add(p.streetView,'Street / surroundings');add(p.photo,'Main place photo');const query=p.placeId||p.googleId||p.cid||[p.name,p.address||q].filter(Boolean).join(', ');if(!query)return out;let d=await api('/google-maps-photos',{query,photosLimit:PHOTO_LIMIT,limit:1,tag:'all',language:'en',region:'US',async:'true'});d=await resolve(d,'Site photos');for(const place of flatten(d))for(const x of(place.photos_data||[]))add(x.photo_url_big||x.photo_url,'Public place photo');return out}
async function load(q,force=false){q=String(q||'').trim();lastLocation=q;if(!isFullAddress(q)){clearPanel(q?'Site Profile requires a full street address; this location will still work for contractor search.':'Enter a full street address to load site/business details and public photos.');return}if(loading)return;loading=true;try{const k=cacheKey(q);let c=await setting(k,null);if(c&&!force&&age(c.refreshedAt)<DETAIL_TTL){render(c);if(age(c.photosRefreshedAt)<PHOTO_TTL)return;status('Site details loaded. Refreshing older photo set…');try{c={...c,photos:await photos(c,q),photosRefreshedAt:NOW()};await saveSetting(k,c);render(c)}catch(e){status('Site details loaded; photo refresh failed: '+e.message)}return}status('Looking up business and property details…');let p=await details(q);if(!p)p={name:'Site / Property',address:q,query:q,photos:[]};p.refreshedAt=NOW();if(c?.photos?.length&&age(c.photosRefreshedAt)<PHOTO_TTL){p.photos=c.photos;p.photosRefreshedAt=c.photosRefreshedAt}render(p);await saveSetting(k,p);if(force||!p.photos?.length||age(p.photosRefreshedAt)>=PHOTO_TTL){status('Site details loaded. Collecting public building/place photos…');try{p={...p,photos:await photos(p,q),photosRefreshedAt:NOW()};await saveSetting(k,p);render(p)}catch(e){status('Site details loaded; public photo lookup did not complete: '+e.message)}}}catch(e){status(e.message||String(e))}finally{loading=false}}
async function init(){installLayout();db=await openDb();const loc=$('location');if(!loc)return;clearPanel();$('searchBtn')?.addEventListener('click',()=>setTimeout(()=>load(loc.value,false),0),true);$('refreshBtn')?.addEventListener('click',()=>setTimeout(()=>load(loc.value,true),0),true);loc.addEventListener('change',()=>{if(isFullAddress(loc.value))load(loc.value,false);else clearPanel('Site Profile requires a full street address; this location will still work for contractor search.')});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&loc.value&&loc.value!==lastLocation&&isFullAddress(loc.value))load(loc.value,false)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(()=>{}));else init().catch(()=>{});
})();
